spring:
  datasource:
    url: # jdbc:mariadb://127.0.0.1:3306/accsaber_db
    username: # acc
    password: # acc
    hikari:
      maximum-pool-size: 20
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: # true

springfox:
  documentation:
    enabled: false

logging:
  level:
    de.ixsen: TRACE

accsaber:
  disable-score-fetching: true
  disable-avatar-fetching: true
  disable-rank-snapshots: true
  recalculate-ap-on-startup: false
  reload-song-covers-on-startup: false
  score-fetch-intervall-millis: 600000
  avatar-fetch-intervall-millis: 86400000
  rank-snapshot-intervall-millis: 21600000 # every 6 hours
  allowed-origins: # http://localhost:4200,localhost:8080,http://127.0.0.1:4200
  image-save-location: # path/to/folder
  playlist-url: https://api.accsaber.com/playlists/
  image-serving-url: https://cdn.accsaber.com/
  fetch-thread-pool: 10

  connector-user-agent: AccSaber
  enable-curve-query: false
  swagger-host: #

  auth:
    secret: replacethissecretwitharealsecret
    expiration-time: 3_600_000
