spring:
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/accsaber_db
    driver-class-name: org.mariadb.jdbc.Driver
    username: acc
    password: acc
    platform: mariadb
  jpa:
    database: sql_server
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
    show-sql: true

logging:
  level:
    de.ixsen: TRACE
#  file:
#    name: logs/accsaber.log
accsaber:
  disable-score-fetching: true
  disable-avatar-fetching: false
  recalculate-ap-on-startup: false
  reload-song-covers-on-startup: false
  score-fetch-intervall-millis: 600000
  avatar-fetch-intervall-millis: 86400000
  allowed-origins: http://localhost:4200,localhost:8080,http://127.0.0.1:4200
  image-save-location: C:\Users\Ixsen\Projects\accsaber\images

  auth:
    secret: replacethissecretwitharealsecret
    expiration-time: 3_600_000